version: "3"
services:
  sample-register-db:
    image: postgres:11
    container_name: samples-register-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=samples-register
    ports:
      - 5432:5432
    networks:
      - pg
  sample-api:
    build: "./back/"
    container_name: samples-register-api
    restart: always
    depends_on:
      - sample-register-db
    environment:
      STARTUP_DELAY: 10
    ports:
      - 80:80
    networks:
      - pg
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - pg

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - pg
networks:
  pg:
